services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: pausepi
        restart: unless-stopped
        ports:
            - "${APP_PORT:-8000}:8000"
        volumes:
            - .:/var/www
            - ./docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/zzz-local.ini
        env_file:
            - path: .env
              required: false
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
