services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.3-fpm
        container_name: pausepi-php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - app-volume:/var/www
            - ./docker/php/conf.d/:/usr/local/etc/php/conf.d/
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: pausepi-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - app-volume:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    app-volume:
